import type { Metadata } from "next";
import "./globals.css";
import { montserrat, inter } from "./fonts";
import Providers from "./providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${montserrat.variable} antialiased font-mont`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
